/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tictactoe;

import javax.swing.JOptionPane;

/**
 *
 * @author Allen Kurt
 */
public class TicTacToe extends javax.swing.JFrame {
    
    int[] buttonUsed = {0, 0, 0, 0, 0, 0, 0, 0, 0};
    int[] xBox = {0, 0, 0, 0, 0, 0, 0, 0, 0};
    int[] oBox = {0, 0, 0, 0, 0, 0, 0, 0, 0};
    
    
    int checkX() {
        if (xBox[0] == 1 && xBox[1] == 1 && xBox[2] == 1) {
            return 1;
        }
        if (xBox[3] == 1 && xBox[4] == 1 && xBox[5] == 1) {
            return 1;
        }
        if (xBox[6] == 1 && xBox[7] == 1 && xBox[8] == 1) {
            return 1;
        }
        if (xBox[0] == 1 && xBox[3] == 1 && xBox[6] == 1) {
            return 1;
        }
        if (xBox[1] == 1 && xBox[4] == 1 && xBox[7] == 1) {
            return 1;
        }
        if (xBox[2] == 1 && xBox[5] == 1 && xBox[8] == 1) {
            return 1;
        }
        if (xBox[0] == 1 && xBox[4] == 1 && xBox[8] == 1) {
            return 1;
        }
        if (xBox[2] == 1 && xBox[4] == 1 && xBox[6] == 1) {
            return 1;
        }
        return 0;
    }
    
    int checkO() {
        if (oBox[0] == 1 && oBox[1] == 1 && oBox[2] == 1) {
            return 1;
        }
        if (oBox[3] == 1 && oBox[4] == 1 && oBox[5] == 1) {
            return 1;
        }
        if (oBox[6] == 1 && oBox[7] == 1 && oBox[8] == 1) {
            return 1;
        }
        if (oBox[0] == 1 && oBox[3] == 1 && oBox[6] == 1) {
            return 1;
        }
        if (oBox[1] == 1 && oBox[4] == 1 && oBox[7] == 1) {
            return 1;
        }
        if (oBox[2] == 1 && oBox[5] == 1 && oBox[8] == 1) {
            return 1;
        }
        if (oBox[0] == 1 && oBox[4] == 1 && oBox[8] == 1) {
            return 1;
        }
        if (oBox[2] == 1 && oBox[4] == 1 && oBox[6] == 1) {
            return 1;
        }
        return 0;
    }
    
    void computerMove() {
        javax.swing.JButton[] buttons = {btn0, btn1, btn2, btn3, btn4, btn5, btn6, btn7, btn8};
        int remaining = 0;
        for (int btn: buttonUsed ) {
            if (btn == 0) remaining++;
        }
                
        int move = (int) (Math.random() * remaining) + 1;
        int counter = 0;
        for (int i = 0; i < 9; i++) {
            if (buttonUsed[i] == 0) {
                counter++;
                if (counter == move) {
                    buttonUsed[i] = 1;
                    oBox[i] = 1;
                    buttons[i].setText("O");
                }
            }
           
        }
    }
    
    int checkDraw() {
        int remaining = 0;
        for (int btn: buttonUsed ) {
            if (btn == 0) remaining++;
        }
        if (remaining == 0) return 1;
        return 0;
    }
    
    public TicTacToe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn0 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TicTacToe vs  Computer");

        jPanel1.setBackground(new java.awt.Color(215, 235, 186));

        btn8.setBackground(new java.awt.Color(235, 212, 148));
        btn8.setFont(new java.awt.Font("Tahoma", 1, 72)); // NOI18N
        btn8.setForeground(new java.awt.Color(255, 0, 0));
        btn8.setBorder(new javax.swing.border.MatteBorder(null));
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("TIC TAC TOE GAME");

        btn0.setBackground(new java.awt.Color(235, 212, 148));
        btn0.setFont(new java.awt.Font("Tahoma", 1, 72)); // NOI18N
        btn0.setForeground(new java.awt.Color(255, 0, 0));
        btn0.setBorder(new javax.swing.border.MatteBorder(null));
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });

        btn1.setBackground(new java.awt.Color(235, 212, 148));
        btn1.setFont(new java.awt.Font("Tahoma", 1, 72)); // NOI18N
        btn1.setForeground(new java.awt.Color(255, 0, 0));
        btn1.setBorder(new javax.swing.border.MatteBorder(null));
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setBackground(new java.awt.Color(235, 212, 148));
        btn2.setFont(new java.awt.Font("Tahoma", 1, 72)); // NOI18N
        btn2.setForeground(new java.awt.Color(255, 0, 0));
        btn2.setBorder(new javax.swing.border.MatteBorder(null));
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setBackground(new java.awt.Color(235, 212, 148));
        btn3.setFont(new java.awt.Font("Tahoma", 1, 72)); // NOI18N
        btn3.setForeground(new java.awt.Color(255, 0, 0));
        btn3.setBorder(new javax.swing.border.MatteBorder(null));
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn4.setBackground(new java.awt.Color(235, 212, 148));
        btn4.setFont(new java.awt.Font("Tahoma", 1, 72)); // NOI18N
        btn4.setForeground(new java.awt.Color(255, 0, 0));
        btn4.setBorder(new javax.swing.border.MatteBorder(null));
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn5.setBackground(new java.awt.Color(235, 212, 148));
        btn5.setFont(new java.awt.Font("Tahoma", 1, 72)); // NOI18N
        btn5.setForeground(new java.awt.Color(255, 0, 0));
        btn5.setBorder(new javax.swing.border.MatteBorder(null));
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn6.setBackground(new java.awt.Color(235, 212, 148));
        btn6.setFont(new java.awt.Font("Tahoma", 1, 72)); // NOI18N
        btn6.setForeground(new java.awt.Color(255, 0, 0));
        btn6.setBorder(new javax.swing.border.MatteBorder(null));
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn7.setBackground(new java.awt.Color(235, 212, 148));
        btn7.setFont(new java.awt.Font("Tahoma", 1, 72)); // NOI18N
        btn7.setForeground(new java.awt.Color(255, 0, 0));
        btn7.setBorder(new javax.swing.border.MatteBorder(null));
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btnreset.setBackground(new java.awt.Color(254, 255, 190));
        btnreset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnreset.setText("RESET");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnreset)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(btnreset)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        if (buttonUsed[6] == 1) {
            JOptionPane.showMessageDialog(rootPane, "Button already pressed!!", "Error", JOptionPane.PLAIN_MESSAGE);
        }
        else {
            btn6.setText("×");
            buttonUsed[6] = 1;
            xBox[6] = 1;
            
            computerMove();
            
            int resultX = checkX();
            int resultO = checkO();
            
           
            if (resultX == 1) {
                JOptionPane.showMessageDialog(rootPane, "Player X won!!!", "Congratulations", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
                TicTacToe frame = new TicTacToe();
                frame.setVisible(true);
                
            }
            else if (resultO == 1) {
                JOptionPane.showMessageDialog(rootPane, "Player O won!!!", "Congratulations", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
                TicTacToe frame = new TicTacToe();
                frame.setVisible(true);
            }
            else if (checkDraw() == 1) {
                JOptionPane.showMessageDialog(rootPane, "Draw!!!", "Draw!!!", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
                TicTacToe frame = new TicTacToe();
                frame.setVisible(true);
            }
        }
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed

        if (buttonUsed[0] == 1) {
            JOptionPane.showMessageDialog(rootPane, "Button already pressed!!", "Error", JOptionPane.PLAIN_MESSAGE);
        }
        else {
            btn0.setText("×");
            buttonUsed[0] = 1;
            xBox[0] = 1;
            
            computerMove();
            
            
            int resultX = checkX();
            int resultO = checkO();
            
            if (resultX == 1) {
                JOptionPane.showMessageDialog(rootPane, "Player X won!!!", "Congratulations", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
                TicTacToe frame = new TicTacToe();
                frame.setVisible(true);
                
            }
            else if (resultO == 1) {
                JOptionPane.showMessageDialog(rootPane, "Player O won!!!", "Congratulations", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
                TicTacToe frame = new TicTacToe();
                frame.setVisible(true);
            }
            else if (checkDraw() == 1) {
                JOptionPane.showMessageDialog(rootPane, "Draw!!!", "Draw!!!", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
                TicTacToe frame = new TicTacToe();
                frame.setVisible(true);
            }
        }
        
    }//GEN-LAST:event_btn0ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        if (buttonUsed[1] == 1) {
            JOptionPane.showMessageDialog(rootPane, "Button already pressed!!", "Error", JOptionPane.PLAIN_MESSAGE);
        }
        else {
            btn1.setText("×");
            buttonUsed[1] = 1;
            xBox[1] = 1;
            
            computerMove();
            
            
            int resultX = checkX();
            int resultO = checkO();
            
            if (resultX == 1) {
                JOptionPane.showMessageDialog(rootPane, "Player X won!!!", "Congratulations", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
                TicTacToe frame = new TicTacToe();
                frame.setVisible(true);
                
            }
            else if (resultO == 1) {
                JOptionPane.showMessageDialog(rootPane, "Player O won!!!", "Congratulations", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
                TicTacToe frame = new TicTacToe();
                frame.setVisible(true);
            }
            else if (checkDraw() == 1) {
                JOptionPane.showMessageDialog(rootPane, "Draw!!!", "Draw!!!", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
                TicTacToe frame = new TicTacToe();
                frame.setVisible(true);
            }
        }
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        if (buttonUsed[2] == 1) {
            JOptionPane.showMessageDialog(rootPane, "Button already pressed!!", "Error", JOptionPane.PLAIN_MESSAGE);
        }
        else {
            btn2.setText("×");
            buttonUsed[2] = 1;
            xBox[2] = 1;
            
            computerMove();
            
            
            int resultX = checkX();
            int resultO = checkO();
            
            if (resultX == 1) {
                JOptionPane.showMessageDialog(rootPane, "Player X won!!!", "Congratulations", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
                TicTacToe frame = new TicTacToe();
                frame.setVisible(true);
                
            }
            else if (resultO == 1) {
                JOptionPane.showMessageDialog(rootPane, "Player O won!!!", "Congratulations", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
                TicTacToe frame = new TicTacToe();
                frame.setVisible(true);
            }
            else if (checkDraw() == 1) {
                JOptionPane.showMessageDialog(rootPane, "Draw!!!", "Draw!!!", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
                TicTacToe frame = new TicTacToe();
                frame.setVisible(true);
            }
        }
    }//GEN-LAST:event_btn2ActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        for (int i = 0; i < 9; i++) {
            buttonUsed[i] = 0;
            xBox[i] = 0;
            oBox[i] = 0;
        }
        
        btn0.setText("");
        btn1.setText("");
        btn2.setText("");
        btn3.setText("");
        btn4.setText("");
        btn5.setText("");
        btn6.setText("");
        btn7.setText("");
        btn8.setText("");
    }//GEN-LAST:event_btnresetActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        if (buttonUsed[3] == 1) {
            JOptionPane.showMessageDialog(rootPane, "Button already pressed!!", "Error", JOptionPane.PLAIN_MESSAGE);
        }
        else {
            btn3.setText("×");
            buttonUsed[3] = 1;
            xBox[3] = 1;
            
            computerMove();
            
            
            int resultX = checkX();
            int resultO = checkO();
            
            if (resultX == 1) {
                JOptionPane.showMessageDialog(rootPane, "Player X won!!!", "Congratulations", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
                TicTacToe frame = new TicTacToe();
                frame.setVisible(true);
                
            }
            else if (resultO == 1) {
                JOptionPane.showMessageDialog(rootPane, "Player O won!!!", "Congratulations", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
                TicTacToe frame = new TicTacToe();
                frame.setVisible(true);
            }
            else if (checkDraw() == 1) {
                JOptionPane.showMessageDialog(rootPane, "Draw!!!", "Draw!!!", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
                TicTacToe frame = new TicTacToe();
                frame.setVisible(true);
            }
        }    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        if (buttonUsed[4] == 1) {
            JOptionPane.showMessageDialog(rootPane, "Button already pressed!!", "Error", JOptionPane.PLAIN_MESSAGE);
        }
        else {
            btn4.setText("×");
            buttonUsed[4] = 1;
            xBox[4] = 1;
            
            computerMove();
            
            
            int resultX = checkX();
            int resultO = checkO();
            
            if (resultX == 1) {
                JOptionPane.showMessageDialog(rootPane, "Player X won!!!", "Congratulations", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
                TicTacToe frame = new TicTacToe();
                frame.setVisible(true);
                
            }
            else if (resultO == 1) {
                JOptionPane.showMessageDialog(rootPane, "Player O won!!!", "Congratulations", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
                TicTacToe frame = new TicTacToe();
                frame.setVisible(true);
            }
            else if (checkDraw() == 1) {
                JOptionPane.showMessageDialog(rootPane, "Draw!!!", "Draw!!!", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
                TicTacToe frame = new TicTacToe();
                frame.setVisible(true);
            }
        }
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        if (buttonUsed[5] == 1) {
            JOptionPane.showMessageDialog(rootPane, "Button already pressed!!", "Error", JOptionPane.PLAIN_MESSAGE);
        }
        else {
            btn5.setText("×");
            buttonUsed[5] = 1;
            xBox[5] = 1;
            
            computerMove();
            
            
            int resultX = checkX();
            int resultO = checkO();
            
            if (resultX == 1) {
                JOptionPane.showMessageDialog(rootPane, "Player X won!!!", "Congratulations", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
                TicTacToe frame = new TicTacToe();
                frame.setVisible(true);
                
            }
            else if (resultO == 1) {
                JOptionPane.showMessageDialog(rootPane, "Player O won!!!", "Congratulations", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
                TicTacToe frame = new TicTacToe();
                frame.setVisible(true);
            }
            else if (checkDraw() == 1) {
                JOptionPane.showMessageDialog(rootPane, "Draw!!!", "Draw!!!", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
                TicTacToe frame = new TicTacToe();
                frame.setVisible(true);
            }
        }
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        if (buttonUsed[7] == 1) {
            JOptionPane.showMessageDialog(rootPane, "Button already pressed!!", "Error", JOptionPane.PLAIN_MESSAGE);
        }
        else {
            btn7.setText("×");
            buttonUsed[7] = 1;
            xBox[7] = 1;
            
            computerMove();
            
            
            int resultX = checkX();
            int resultO = checkO();
            
            if (resultX == 1) {
                JOptionPane.showMessageDialog(rootPane, "Player X won!!!", "Congratulations", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
                TicTacToe frame = new TicTacToe();
                frame.setVisible(true);
                
            }
            else if (resultO == 1) {
                JOptionPane.showMessageDialog(rootPane, "Player O won!!!", "Congratulations", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
                TicTacToe frame = new TicTacToe();
                frame.setVisible(true);
            }
            else if (checkDraw() == 1) {
                JOptionPane.showMessageDialog(rootPane, "Draw!!!", "Draw!!!", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
                TicTacToe frame = new TicTacToe();
                frame.setVisible(true);
            }
        }
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        if (buttonUsed[8] == 1) {
            JOptionPane.showMessageDialog(rootPane, "Button already pressed!!", "Error", JOptionPane.PLAIN_MESSAGE);
        }
        else {
            btn8.setText("×");
            buttonUsed[8] = 1;
            xBox[8] = 1;
            
            computerMove();
            
            
            int resultX = checkX();
            int resultO = checkO();
            
            if (resultX == 1) {
                JOptionPane.showMessageDialog(rootPane, "Player X won!!!", "Congratulations", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
                TicTacToe frame = new TicTacToe();
                frame.setVisible(true);
                
            }
            else if (resultO == 1) {
                JOptionPane.showMessageDialog(rootPane, "Player O won!!!", "Congratulations", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
                TicTacToe frame = new TicTacToe();
                frame.setVisible(true);
            }
            else if (checkDraw() == 1) {
                JOptionPane.showMessageDialog(rootPane, "Draw!!!", "Draw!!!", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
                TicTacToe frame = new TicTacToe();
                frame.setVisible(true);
            }
        }
    }//GEN-LAST:event_btn8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicTacToe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btnreset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
